server:
  port: 9000

spring:
  application:
    name: class-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.0.8:8848
    #sentinel配置
    sentinel:
      transport:
        dashboard: 10.0.0.8:8858
        #8710-8730
        port: 8000

  datasource:
    url: jdbc:mysql://10.0.0.8:3306/cloud_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    druid:
      initial-size: 5 # 初始连接数
      min-idle: 10 # 最小连接池数量
      max-active: 20 # 最大连接池数量
      max-wait: 600000 # 配置获取连接等待超时的时间，单位：毫秒
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位：毫秒
      max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位：毫秒
      validation-query: SELECT 1 # 配置检测连接是否有效

mybatis-plus:
  configuration:
    #打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  #指定映射文件路径,默认classpath*:/mapper/**/*.xml
  mapper-locations: classpath*:/mapper/**/*.xml
  #设置类型别名
  type-aliases-package: online.superh.common.domain

#负载均衡策略
#调用video服务时的策略
class-video-service:
  ribbon:
    NFLoadBalancerRuleClassName:
      com.netflix.loadbalancer.RandomRule