server:
  port: 7000
spring:
  application:
    name: class-api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.0.8:8848
    gateway:
      routes:
        - id: class-order-service
          uri: lb://class-order-service #从nacos获取名称转发,lb是负载均衡轮训策略
          order: 1 #优先级，数字越⼩优先级越⾼
          predicates:
            - Path=/class-order-service/api/v1/order/**
          filters: #过滤器，请求在传递过程中通过过滤器修改
            - StripPrefix=1 #去掉第⼀层前缀
      discovery:
        locator:
          enabled: true #开启⽹关拉取nacos的服务